---
title: statistician
author: heeryun
---

## Q1  - Are men more likely than women to say yes to a second date?

Conduct a hypothesis test on whether the men are more likely than women 
to say yes to a second date.

**H0 men are equally likely to say yes to another date**
**HA men are more likely to say yes to another date**

$$
H0: \mu_M = \mu_F \\HA: \mu_M > \mu_F
$$


## Q2 What value do *men* find most important when considering a second date?

note: Maybe we visualize this using side by side boxplots?
average rating by decision - that way we can see which variable seems to differenciate between a yes and a no
compare average rating per trait per yes/no response
Which category's ratings has the greatest differece between yes/no?

ALTERNATIVELY: 
Calculate the chi-squared test of independence and p-value for all categories and compare  the p-values.


## Q3 What value do *women* find most important when considering a second date?

average rating by decision - that way we can see which variable seems to differenciate between a yes and a no
compare average rating per trait per yes/no response
Which category's ratings has the greatest differece between yes/no?

ALTERNATIVELY: 
Calculate the chi-squared test of independence and p-value for all categories and compare  the p-values.


## Q4 Do larger age gaps play a factor when considering another date?

Conduct a hypothesis test on whether the two variables have a correlation.

**H0: Age gap size don't affect whether there is a second date or not.**
**HA: Age gap size affects whether there is a second date or not.**

$$
H_0: \rho = 0 \\ H_A: \rho > 0
$$

